name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_NPM_LEGACY_INSTALL: false
      NX_CLOUD_NPM_INSTALL_TIMEOUT: 600
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install --prefer-offline --no-audit --no-fund --no-optional
        timeout-minutes: 8

      # --- Future: Playwright setup (uncomment when needed) ---
      # - name: Install Playwright
      #   run: npx playwright install --with-deps
      #   timeout-minutes: 5

      # Start Nx Cloud after dependencies are installed
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="ci"

      # Run lint, test, build with Nx Cloud recording
      - run: npx nx-cloud record -- npx nx run-many -t lint test build

      # --- Future: e2e target (uncomment when needed) ---
      # - run: npx nx-cloud record -- npx nx run-many -t e2e

      # Nx Cloud recommends fixes for failures to help you get CI green faster
      - run: npx nx-cloud record -- npx nx fix-ci
        if: always()

      # --- Future: matrix build example ---
      # strategy:
      #   matrix:
      #     node: [18, 20]
      # runs-on: ubuntu-latest
      # steps:
      #   - uses: actions/setup-node@v4
      #     with:
      #       node-version: ${{ matrix.node }}
      #       cache: 'npm'
