name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_NPM_LEGACY_INSTALL: false
      NX_CLOUD_NPM_INSTALL_TIMEOUT: 600
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache node_modules + npm cache
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Deterministic install
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --no-fund
        timeout-minutes: 8

      - name: Install Playwright
        run: npx playwright install --with-deps
        timeout-minutes: 5

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Run distributed Nx tasks
      - run: npx nx affected -t lint test build e2e --parallel

      - run: npx nx-cloud record -- npx nx fix-ci
        if: always()
