name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies with timeout
      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund
        timeout-minutes: 10

      - name: Install Playwright
        run: npx playwright install --with-deps
        timeout-minutes: 5

      # Run Nx commands with cloud recording
      - run: npx nx-cloud record -- npx nx run-many -t lint test build e2e
      
      # Nx Cloud recommends fixes for failures to help you get CI green faster
      - run: npx nx-cloud record -- npx nx fix-ci
        if: always()