name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_NPM_LEGACY_INSTALL: false
      NX_CLOUD_NPM_INSTALL_TIMEOUT: 600

    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Setup Node and enable npm caching
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install dependencies (fast + stable)
      - name: Install dependencies
        run: |
          npm install --prefer-offline --no-audit --no-fund --no-optional
        timeout-minutes: 8

      # Install Playwright (commented until needed)
      # - name: Install Playwright
      #   run: npx playwright install --with-deps
      #   timeout-minutes: 5

      # Start Nx Cloud distributed agents
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      # Run Nx tasks in parallel on Nx Cloud
      - run: npx nx-cloud record -- npx nx run-many -t lint test build --parallel=3

      # Run Nx Cloud fix (always runs, even if previous failed)
      - run: npx nx-cloud record -- npx nx fix-ci
        if: always()

      # Example for future: add e2e back
      # - run: npx nx-cloud record -- npx nx run-many -t e2e
